### PR TITLE
Added support for brazilian portuguese

### PR DESCRIPTION
**Pull request by spyker0**
I also increased the version to 1.1.0

### CODE REVIEW

**Comment by Carl-Hugo** [comment]
Thanks for the translation.

Is there any significant difference between Portuguese (`pt`) and `pt-BR` that could justify not using your translation as the default Portuguese messages?

If there is no difference, could you please rename the `pt-BR` to simply `pt` so we have a default Portuguese language first? Thanks in advance

**Comment by Carl-Hugo** [comment]
So you don't think that there is a way to create a default Portuguese translation? I am clueless about Portuguese tbh.

**Comment by spyker0** [comment]
I think there is, anyway, we need a person that know more about european portuguese.
In my opinion you should keep this translation in pt-BR and someone in the future can make a translation to european portuguese.

**Comment by Carl-Hugo** [comment]
I think that it is important to have a neutral-culture (`pt`) where both culture-specific `pt-BR` and `pt-PT` could fallback to, even if it is not perfect for everyone, at least it is there.

I see two ways of doing this:

1. We rename `pt-BR` to `pt` and specify in the readme that the default is Brazilian. If someone from Portugal wants a better translation, he then can contribute it under `pt-PT`, and if some language guru finds a good way to create a good `pt` translation, we can always rename yours to `pt-BR` later and create a new `pt` one.
2. We copy your `pt-BR` as `pt`, so we have a culture-neutral fallback and a culture-specific translation (the same), then someone else could try to fine tune `pt`, and someone from Portugal could add a `pt-PT` language later.

I leave you to choose the way that you prefer; I see advantages and disadvantages with both ways, so I don't mind either. 

Once that is done, I will merge your PR and deploy the v1.1 on NuGet for you to consume.

**Comment by spyker0** [comment]
Nice, I think the second option it's fine!
I'll do that!

**Comment by spyker0** [comment]
Thank you!

**Pull request merged**
