### PR TITLE
es-MX traslation

### PR DESCRIPTION
**Pull request by OswaldoDG**
Hi, es-MX available.

### CODE REVIEW

**Comment by Carl-Hugo** [comment]
Perfect, thanks

**Comment by Carl-Hugo** [comment]
The package should be available on NuGet.org soon, version 1.2.0; thanks for the translation!

**Comment by OswaldoDG** [comment]
You're welcome, nice work very useful library.

I'll check your other projects.

Regards

El 17/01/2019 7:37 p.m., Carl-Hugo Marcotte <notifications@github.com> escribió:

The package should be available on NuGet.org soon, version 1.2.0; thanks for the translation!

**Comment by Carl-Hugo** [comment]
For my other projects, I suggest that you start by the [Table of Content](https://github.com/ForEvolve/Toc) repo.

**Pull request merged**
