### PR TITLE
Added support for Norwegian (bokmål)

### PR DESCRIPTION
**Pull request by petterhoel**
Hi, 

Great project, very useful. Please consider this addition of support for the most common Norwegian Culture. 

I have translated, spell checked, added the culture, updated the readme and run the tests. Let me know if there is else needed. 

Thanks, 
Petter

### CODE REVIEW

**Comment by Carl-Hugo** [comment]
Thanks for the contributing and glad you like the project.

I am not familiar with the Norwegian culture and sub-cultures, but could your translation be used as the default Norwegian (bokmål) neutral culture ( `nb` only) instead of only a culture specific to Norway (`nb-NO`)?

- If it is possible, could you please rename `nb-NO` to `nb`.
- If that's two different thing, could you duplicate `nb-NO` to `nb` so we have a tweakable default and a culture specific one.
- If `nb` is not a thing, please disregard my comment and enlighten me so I can merge your PR and learn a thing or two about the Norwegian Culture along the way 😉 

**Reference (README):**
> If you want to create a culture-specific translation, example: `fr-CA`, please make sure that there is an `fr` translation (neutral culture) first which will be the default for that language.

**Comment by Carl-Hugo** [comment]
Note: the build seems broken from my end (I played in my pipeline a lot recently) so you have nothing to fix there.

**Comment by petterhoel** [comment]
I'm not very proficient in locales, but in my experience people use both `nb` and `nb-NO` all though they mean the same thing. Most often I see `nb-NO` used. So maybe it would make sense to add `nb` as a duplicate?

**Comment by petterhoel** [comment]
According to [this list](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c) `no` is also an item. They would all be equivalent language wise. Would you like me to add all three?

Screenshot 2019-03-16 at 08 26 49

**Comment by Carl-Hugo** [comment]
Ok, I built a small `CultureInfo` browser (that I will deploy somewhere later) to validate against the .Net Core `CultureInfo` list (just to be sure), and there seems to be three indeed:

- Norwegian Bokmål `nb`
- Norwegian `no`
- Norwegian Bokmål (Norway) `nb-NO`

I am not sure how different would be  `nb` and `nb-NO` but I guess that would be the same.
So I think I'd go for only those two: `nb` and `no`.
Using `nb-NO` should default to `nb` anyway, so all three should be covered.

What do you think?

My filtered results:
image

**Comment by petterhoel** [comment]
That sounds good. Good to know that `nb-NO` will fall back to `nb`. I was not aware, thanks. 

I have added made changes to support `nb` and `no`, updated readme, including code highlighting of culture names for clarity. Let me know if you don't like that. 

Should be good to go otherwise.

**Comment by Carl-Hugo** [comment]
Sounds good to me.

About the "fallback," basically if there is no culture-specific translation it falls back to the culture neutral; if there is no culture-neutral, it falls back to the default (which in this case is english); clever .Net 😉 

I will start a "release build" and deploy your PR to NuGet hopefully today.

**Pull request merged**
